// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBoU8egj7Y5ej4Mx2diyp6oEF0TakD5dMo',
    appId: '1:866779071647:android:56e67afe72db0012608eaa',
    messagingSenderId: '866779071647',
    projectId: 'template-952d1',
    storageBucket: 'template-952d1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDjnDEThWQ0nHI4hEURGYl5jGBjMp09rW8',
    appId: '1:866779071647:ios:fa16f26a6545f05b608eaa',
    messagingSenderId: '866779071647',
    projectId: 'template-952d1',
    storageBucket: 'template-952d1.appspot.com',
    iosClientId: '866779071647-tugvddaoftld14vah6fb4ts64jvl0n0h.apps.googleusercontent.com',
    iosBundleId: 'com.lukaszsinica.template',
  );
}
